steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '--target', 'production', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-secrets'
      - >-
        DB_HOST=DB_HOST:latest,
        DB_NAME=DB_NAME:latest,
        DB_USER=DB_USER:latest,
        DB_PASSWORD=DB_PASSWORD:latest,
        JWT_SECRET=jwt-secret:latest

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'civil-forge-403609:us-central1:support-portal-db'