steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:support-portal-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--set-secrets'
      - >-
        CLOUD_SQL_CONNECTION_NAME=CLOUD_SQL_CONNECTION_NAME:latest,
        DB_NAME=DB_NAME:latest,
        DB_USER=DB_USER:latest,
        DB_PASSWORD=DB_PASSWORD:latest,
        STORAGE_BUCKET=STORAGE_BUCKET:latest,
        GMAIL_CLIENT_ID=GMAIL_CLIENT_ID:latest,
        GMAIL_CLIENT_SECRET=GMAIL_CLIENT_SECRET:latest,
        GMAIL_REFRESH_TOKEN=GMAIL_REFRESH_TOKEN:latest,
        JWT_SECRET=jwt-secret:latest

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

options:
  logging: CLOUD_LOGGING_ONLY
