steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - >-
        DB_HOST=DB_HOST:latest,
        DB_PORT=DB_PORT:latest,
        DB_NAME=DB_NAME:latest,
        DB_USER=DB_USER:latest,
        DB_PASSWORD=DB_PASSWORD:latest,
        CLOUD_SQL_CONNECTION_NAME=CLOUD_SQL_CONNECTION_NAME:latest,
        GMAIL_CLIENT_ID=GMAIL_CLIENT_ID:latest,
        GMAIL_CLIENT_SECRET=GMAIL_CLIENT_SECRET:latest,
        GMAIL_REFRESH_TOKEN=GMAIL_REFRESH_TOKEN:latest,
        jwt-secret=jwt-secret:latest,
        ADMIN_EMAIL=ADMIN_EMAIL:latest,
        ADMIN_PASSWORD=ADMIN_PASSWORD:latest

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'civil-forge-403609:us-central1:support-portal-db'

# Trigger configuration
triggers:
  - github:
      owner: "Appraisily"
      name: "support-portal-backend"
      push:
        branch: "^main$"
    pubsub:
      topic: "cloud-builds"
    webhook: true

# Files that trigger builds
includedFiles:
  - 'src/**'
  - 'package*.json'
  - 'Dockerfile'
  - 'cloudbuild.yaml'
  - '.dockerignore'