steps:
  # Construir la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '.']
  
  # Empujar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:support-portal-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,STORAGE_BUCKET=support-portal-attachments-$PROJECT_ID,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID'
      - '--vpc-connector'
      - 'projects/$PROJECT_ID/locations/us-central1/connectors/cloud-sql-connector'

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

options:
  logging: CLOUD_LOGGING_ONLY
