steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '--target', 'production', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Run database migrations
  - name: 'gcr.io/$PROJECT_ID/support-portal-backend'
    entrypoint: 'node'
    args: ['node_modules/.bin/sequelize-cli', 'db:migrate']
    env:
      - 'NODE_ENV=production'
      - 'DB_HOST=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME}'
      - 'DB_NAME=${_DB_NAME}'
      - 'DB_USER=${_DB_USER}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-secrets'
      - >-
        DB_HOST=DB_HOST:latest,
        DB_NAME=DB_NAME:latest,
        DB_USER=DB_USER:latest,
        DB_PASSWORD=DB_PASSWORD:latest,
        JWT_SECRET=jwt-secret:latest,
        OPENAI_API_KEY=OPENAI_API_KEY:latest,
        SALES_SPREADSHEET_ID=SALES_SPREADSHEET_ID:latest,
        PENDING_APPRAISALS_SPREADSHEET_ID=PENDING_APPRAISALS_SPREADSHEET_ID:latest,
        COMPLETED_APPRAISALS_SPREADSHEET_ID=COMPLETED_APPRAISALS_SPREADSHEET_ID:latest

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'civil-forge-403609:us-central1:support-portal-db'
  _DB_NAME: 'support_portal'
  _DB_USER: 'support_portal_user'