steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/support-portal-backend', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/support-portal-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'support-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/support-portal-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:support-portal-db'
      - '--service-account'
      - 'support-portal-backend@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,STORAGE_BUCKET=support-portal-attachments-$PROJECT_ID,CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:us-central1:support-portal-db,DB_NAME=support_portal,DB_USER=support_portal_user'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'

images:
  - 'gcr.io/$PROJECT_ID/support-portal-backend'

options:
  logging: CLOUD_LOGGING_ONLY
