version: '3.8'

services:
  test:
    build: 
      context: .
      target: development
    environment:
      - NODE_ENV=test
      - DB_HOST=test-db
      - DB_PORT=5432
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - test-db
    command: npm test

  test-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres