version: '3.8'

services:
  api:
    build: 
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=support_portal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=local-dev-secret
      - ADMIN_EMAIL=admin@appraisily.com
      - ADMIN_PASSWORD=admin123
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=support_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: